Adding Process Actions
crossroads/api.goodcity pull request #1179
Opened 2020-12-14 06:55 UTC by bharat619

### Ticket Link: 
https://jira.crossroads.org.hk/browse/GCW-3427

### What does this PR do?
Add source to Process actions

2020-12-16 07:35 UTC, shreyas098 approved these changes

2020-12-16 08:07 UTC, patrixr requested changes
Small changes, nothing major

2020-12-16 08:07 UTC, patrixr commented on app/models/processing_destinations_lookup.rb
> +class ProcessingDestinationsLookup < ApplicationRecord
I feel the name `ProcessingDestinationsLookup` is unnecessarily long. `ProcessingDestination` is more than enough

2020-12-16 08:07 UTC, patrixr commented on app/models/processing_destinations_lookup.rb
> +class ProcessingDestinationsLookup < ApplicationRecord
also it would kinda mean that the db table is a table of lookups
whereas it _is_ a lookup table, of processing destinations

2020-12-16 08:07 UTC, patrixr commented on app/models/concerns/operations/stock_operations.rb
> +    def register_quantity_change(package, quantity:, location:, action:, description: nil, source: nil, processing_destination_lookup_id: nil)
That parameter doesn't have its place here. Please remove that. 
The processing destination _is_ a source, which is already in the params.

The _caller_ of this method should pass in the source

2020-12-16 08:07 UTC, patrixr commented on app/controllers/api/v1/packages_controller.rb
> +          processing_destination_lookup_id: params[:processing_destination_lookup_id],
Set the source correctly _here_.

2020-12-17 06:16 UTC, patrixr approved these changes

2020-12-17 08:04 UTC, merged

2020-12-18 04:37 UTC, steveyken reviewed
Good job